### ISSUE TITLE
Consolidate/use the SimoTodd Turbolinks Bridge

### ISSUE THREAD

**Issue by pspeter3** [gohugoio/hugo-mod-jslibs#3]
What's the difference between your Turbolinks bridge and https://github.com/SimoTod/alpine-turbolinks-adapter?

**Comment by bep** [comment]
I don't kniow.

**Comment by HugoDF** [comment]
They're the same, the turbolinks bridge was developed by Simone in his own namespace (`github.com/SimoTod/`) but was then moved into the Alpine.js organisation and now it's been moved back out.

Since it was moved, pointing to the `alpinejs/` URL should redirect the the current repo.
